spring:
  security:
    oauth2:
      client:
        registration:
          admin-cli:
            client-id: admin-cli
            client-secret: 2gDMXkraIwCMtIR2rCAS8gOZEq75R7Ak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/admin-cli"
            scope: read, write
        provider:
          okta:
            authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token

  idp.provider.keycloak.client-secret=2gDMXkraIwCMtIR2rCAS8gOZEq75R7Ak
  idp.provider.keycloak.client-id=unhrc-bims
  idp.provider.keycloak.realm=unhrc-bims
  idp.provider.keycloak.base-url=http://localhost:8080
  idp.provider.keycloak.token-uri=/realms/unhrc-bims/protocol/openid-connect/token
  idp.provider.keycloak.jwkset-uri=/realms/unhrc-bims/protocol/openid-connect/token
  idp.provider.keycloak.user-uri=/admin/realms/unhrc-bims/users
  idp.provider.keycloak.admin-token-uri=/realms/master/protocol/openid-connect/token
  idp.provider.keycloak.admin-username=admin
  idp.provider.keycloak.admin-password=Pa55w0rd
  idp.provider.keycloak.admin-client-secret=2gDMXkraIwCMtIR2rCAS8gOZEq75R7Ak
  idp.provider.keycloak.admin-client-id=admin-cli