name: Use this to maven cd into EKS
on:
  workflow_dispatch: {}
#on: push
#  issues:
#    types:
#      - opened
jobs:
#  comment:
#    runs-on: ubuntu-latest
#    steps:
#      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ISSUE: ${{ github.event.issue.html_url }}
  code-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          #role-to-assume: ${{ secrets.MAVEN_IAM_ROLE }}
          #role-session-name: GitHub-Action-Role
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and publish
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --region us-east-1 --domain alphaomega-repo --domain-owner 127418365645 --query authorizationToken --output text)
          ./mvnw -s settings.xml clean deploy -P alphaomega-repo-alpha-omega-repo
          ./mvnw -s settings.xml k8s:build
      - name: Push Docker Image
        run: |
          ./mvnw -s settings.xml k8s:build
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 127418365645.dkr.ecr.us-east-1.amazonaws.com
          docker push 127418365645.dkr.ecr.us-east-1.amazonaws.com/user-context-service:latest
          






